const test = require('node:test');
const assert = require('node:assert/strict');
const { extractEquipmentSlots } = require('../src/equipment-slots');
const { render } = require('../public/equipment-hud');
test('uses exact player slots, preserving empty gaps and separate stacks', () => {
  const slots = [];
  slots[36] = { name: 'cobblestone', count: 64 };
  slots[38] = { name: 'cobblestone', count: 12 };
  slots[5] = { name: 'iron_helmet', count: 1 };
  slots[45] = { name: 'shield', count: 1 };
  const result = extractEquipmentSlots({ inventory: { slots }, quickbarSlot: 2 });
  assert.equal(result.hotbar.length, 9);
  assert.equal(result.hotbar[1], null);
  assert.equal(result.hotbar[2].count, 12);
  assert.equal(result.selected, 2);
  assert.equal(result.armor.head.name, 'iron_helmet');
  assert.equal(result.armor.chest, null);
  assert.equal(result.offhand.name, 'shield');
  slots[38].count = 5;
  assert.equal(result.hotbar[2].count, 12, 'snapshot does not retain item references');
});
test('HUD has nine slots, correct selection, clears equipment, and does not invent old-server slots', () => {
  const element = () => ({ children: [], attrs: {}, textContent: '', append(...nodes) { this.children.push(...nodes); }, replaceChildren(...nodes) { this.children = nodes; }, setAttribute(k, v) { this.attrs[k] = v; } });
  const els = { hotbar: element(), armorSlots: element(), equipmentStatus: element() };
  const doc = { createElement: element, getElementById: id => els[id] };
  const slots = [];
  slots[44] = { name: '<script>', count: 7 };
  render(doc, { equipment_slots: extractEquipmentSlots({ inventory: { slots }, quickbarSlot: 8 }) });
  assert.equal(els.hotbar.children.length, 9);
  assert.match(els.hotbar.children[8].className, /selected/);
  assert.equal(els.hotbar.children[8].children[1].textContent, '<script>');
  assert.equal(els.armorSlots.children.length, 5);
  const originalSlot = els.hotbar.children[8];
  render(doc, { equipment_slots: extractEquipmentSlots({ inventory: { slots }, quickbarSlot: 8 }) });
  assert.equal(els.hotbar.children[8], originalSlot, 'unchanged snapshot retains DOM nodes');
  slots[44].count = 8;
  render(doc, { equipment_slots: extractEquipmentSlots({ inventory: { slots }, quickbarSlot: 8 }) });
  assert.notEqual(els.hotbar.children[8], originalSlot, 'changed counts update the HUD');
  render(doc, { inventory: { diamond: 99 } });
  assert.equal(els.hotbar.children[8].children[1].textContent, '未知');
  assert.ok(els.hotbar.children.every(el => !el.className.includes('selected')));
  render(doc, { equipment_slots: extractEquipmentSlots({}) });
  assert.equal(els.hotbar.children[0].children[1].textContent, '空');
});
